//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMO.ADO.NET.Ex03
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customers()
        {
            this.Transactions = new HashSet<Transactions>();
        }
    
        public long CustomerId { get; set; }
        public int CustomerTitleId { get; set; }
        public string CustomerFirstName { get; set; }
        public string CustomerOtherInitials { get; set; }
        public string CustomerLastName { get; set; }
        public long AddressId { get; set; }
        public string AccountNumber { get; set; }
        public int AccountTypeId { get; set; }
        public decimal CleareBalance { get; set; }
        public decimal UncleareBalance { get; set; }
        public System.DateTime DateAdded { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transactions> Transactions { get; set; }
    }
}
