//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMO.ADO.NET.Ex03
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionTypes
    {
        public int TransactionTypesId { get; set; }
        public string TransactionDescription { get; set; }
        public bool CreditType { get; set; }
        public bool AffectCashBalance { get; set; }
    }
}
